package sbt.incrementalcompiler

import xsbti.Problem

/**
 * Represents the output of an incremental compiler run.
 */
trait IncrementalCompilationResult {

  /** The `Analysis` generated by the analyzing compilers used to compile. */
  def analysis: Analysis

  /** The messages logged during compilation. */
  def problems: Array[Problem]

  /** Indicates whether any file has been recompiled during this incremental compiler run. */
  def isModified: Boolean

}
